apiVersion: v1
kind: Secret
metadata:
  name: animagenius-secrets
  namespace: animagenius-production
  labels:
    app: animagenius
    component: secrets
type: Opaque
data:
  # Database credentials (base64 encoded)
  DB_USERNAME: YW5pbWFnZW5pdXM=  # animagenius
  DB_PASSWORD: <base64-encoded-password>
  
  # Redis credentials (base64 encoded)
  REDIS_PASSWORD: <base64-encoded-redis-password>
  
  # JWT Secret
  JWT_SECRET: <base64-encoded-jwt-secret>
  
  # API Keys (base64 encoded)
  OPENAI_API_KEY: <base64-encoded-openai-key>
  ANTHROPIC_API_KEY: <base64-encoded-anthropic-key>
  SYNTHESIA_API_KEY: <base64-encoded-synthesia-key>
  HEYGEN_API_KEY: <base64-encoded-heygen-key>
  REPLICATE_API_KEY: <base64-encoded-replicate-key>
  OPENROUTER_API_KEY: <base64-encoded-openrouter-key>
  
  # AWS credentials (if not using IAM roles)
  AWS_ACCESS_KEY_ID: <base64-encoded-aws-access-key>
  AWS_SECRET_ACCESS_KEY: <base64-encoded-aws-secret-key>
  
  # Session secret
  SESSION_SECRET: <base64-encoded-session-secret>
  
  # Encryption keys
  ENCRYPTION_KEY: <base64-encoded-encryption-key>
  
  # Webhook secrets
  WEBHOOK_SECRET: <base64-encoded-webhook-secret>

---
apiVersion: v1
kind: Secret
metadata:
  name: animagenius-tls
  namespace: animagenius-production
  labels:
    app: animagenius
    component: tls
type: kubernetes.io/tls
data:
  tls.crt: <base64-encoded-tls-certificate>
  tls.key: <base64-encoded-tls-private-key>

---
# External Secrets Operator configuration (if using AWS Secrets Manager)
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: animagenius-production
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyID:
            name: aws-credentials
            key: access-key-id
          secretAccessKey:
            name: aws-credentials
            key: secret-access-key

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: animagenius-external-secrets
  namespace: animagenius-production
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: animagenius-secrets-from-aws
    creationPolicy: Owner
  data:
  - secretKey: DB_PASSWORD
    remoteRef:
      key: animagenius/production/database
      property: password
  - secretKey: REDIS_PASSWORD
    remoteRef:
      key: animagenius/production/redis
      property: password
  - secretKey: JWT_SECRET
    remoteRef:
      key: animagenius/production/app
      property: jwt_secret
  - secretKey: OPENAI_API_KEY
    remoteRef:
      key: animagenius/production/ai
      property: openai_api_key
  - secretKey: ANTHROPIC_API_KEY
    remoteRef:
      key: animagenius/production/ai
      property: anthropic_api_key
  - secretKey: SYNTHESIA_API_KEY
    remoteRef:
      key: animagenius/production/ai
      property: synthesia_api_key
  - secretKey: HEYGEN_API_KEY
    remoteRef:
      key: animagenius/production/ai
      property: heygen_api_key